Repository GDSC-Daejin/project-cubco-backend, pull requests merged in 2025-05, with the labels that each got.

#12 [SECURITY] JWT 인증/인가 구현 + CORS - #2
  cubco-api/build.gradle
  cubco-api/src/main/java/org/cubco/config/SecurityConfig.java
  cubco-api/src/main/java/org/cubco/config/WebConfig.java
  cubco-api/src/main/java/org/cubco/controller/TestController.java
  cubco-api/src/main/java/org/cubco/filter/JwtAuthenticationFilter.java
  cubco-api/src/main/java/org/cubco/security/CustomAccessDeniedHandler.java
  cubco-api/src/main/java/org/cubco/util/JWTutil.java
  cubco-api/src/main/resources/security.properties
  cubco-common/build.gradle
  cubco-common/src/main/java/org/cubco/exception/ErrorCode.java
  cubco-common/src/main/java/org/cubco/response/CommonResponse.java
Labels: june

#17 [REFACTOR] 예외 처리 개선 및 Swagger 명세 분리 - #13
  cubco-api/src/main/java/org/cubco/controller/TestController.java
  cubco-api/src/main/java/org/cubco/exception/GlobalExceptionHandler.java
  cubco-api/src/main/java/org/cubco/swagger/TestApiDocs.java
  cubco-common/src/main/java/org/cubco/exception/ErrorCode.java
  cubco-common/src/main/java/org/cubco/response/CommonResponse.java
Labels: bemay

#21 [chore] 공통 응답 객체 구조 변경 - #20
  cubco-api/src/main/java/org/cubco/controller/TestController.java
  cubco-api/src/main/java/org/cubco/exception/GlobalExceptionHandler.java
  cubco-common/src/main/java/org/cubco/response/CommonResponse.java
Labels: chore, bemay

#25 [FEAT] 쿠폰 API 구현 - #19
  cubco-api/build.gradle
  cubco-api/src/main/java/org/cubco/auth/config/SecurityConfig.java
  cubco-api/src/main/java/org/cubco/controller/CouponController.java
  cubco-api/src/main/java/org/cubco/controller/TestController.java
  cubco-api/src/main/java/org/cubco/dto/coupon/CouponDetailResponse.java
  cubco-api/src/main/java/org/cubco/dto/coupon/CouponImageUpdateRequest.java
  cubco-api/src/main/java/org/cubco/dto/coupon/CouponImageUpdateResponse.java
  cubco-api/src/main/java/org/cubco/dto/coupon/CouponResponse.java
  cubco-api/src/main/java/org/cubco/dto/coupon/CouponUseRequest.java
  cubco-api/src/main/java/org/cubco/dto/coupon/CouponUseResponse.java
  cubco-api/src/main/java/org/cubco/exception/GlobalExceptionHandler.java
  cubco-api/src/main/java/org/cubco/service/CouponService.java
  cubco-api/src/main/java/org/cubco/swagger/CouponApiDocs.java
  cubco-api/src/main/java/org/cubco/swagger/TestApiDocs.java
  cubco-common/src/main/java/org/cubco/exception/CouponForbiddenException.java
  cubco-common/src/main/java/org/cubco/exception/CouponInsufficientCountException.java
  cubco-common/src/main/java/org/cubco/exception/CouponNotFoundException.java
  cubco-common/src/main/java/org/cubco/exception/ErrorCode.java
  cubco-domain/build.gradle
  cubco-domain/src/main/java/org/cubco/coupon/domain/Coupon.java
  cubco-domain/src/main/java/org/cubco/policy/CouponOwnershipPolicy.java
  cubco-domain/src/main/java/org/cubco/policy/CouponRemainingCountPolicy.java
  cubco-domain/src/main/java/org/cubco/policy/CouponUsePolicy.java
  cubco-domain/src/main/java/org/cubco/repository/CouponRepository.java
Labels: feat, bemay
